; PlatformIO Project Configuration File
;
; Naming convention:
;   [env:<deviceType>_<board>_<radioTech>]
;   deviceType: gw (Gateway) or term (Terminal)
;   board: heltec, ttgo, d1, nano, rboard, sensor
;   radioTech: lora, rf95, nrf24

; ======================
; Common Configurations
; ======================

[platform]
monitor_raw = yes
build_flags =
    -D ALEXA_MAX_CLIENTS=3
    -D CORE_DEBUG_LEVEL=0

[esp32]
build_flags =
    -D ALEXA_MAX_CLIENTS=3
    -D CORE_DEBUG_LEVEL=0

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.2
    arduino-libraries/NTPClient @ ^3.2.1
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    https://github.com/ropg/ezTime.git


[esp8266]
build_flags =
    -D ALEXA_MAX_CLIENTS=3
lib_deps = 
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    arduino-libraries/NTPClient @ ^3.2.1
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0
    bblanchon/ArduinoJson@6.19.4
    arduino-libraries/WiFi@^1.2.7
    https://github.com/ropg/ezTime.git


[HeltecV2]
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.2
    sandeepmistry/LoRa @ ^0.8.0
    arduino-libraries/NTPClient @ ^3.2.1
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0
    eiannone/Heltec_Esp32_Display@^0.1.0
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    https://github.com/ropg/ezTime.git

build_flags =
    -D ALEXA_MAX_CLIENTS=3
    -D HELTEC
    -D DISPLAY_ENABLED
    -D DISPLAYHELTEC
    -D LORA
    -D WIFI

[avr]
build_flags = 
    -D MESH
    -D LORA
    -D LORA_PROMISCUOS=true
lib_deps = 
    SoftwareSerial
    seeed-studio/Grove - LoRa Radio 433MHz 868MHz @ ^2.0.0



[env:term_espC3]
platform = espressif32
board = esp32-c3-devkitm-1  ; Placa mais próxima em configuração
framework = arduino
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
monitor_speed = 115200
upload_protocol = esp-builtin
;upload_protocol = esptool
debug_tool = esp-builtin
;upload_protocol = esp-prog
;debug_tool = esp-prog
;upload_port = /dev/cu.usbserial-XXXX  ; No Windows: COMX
;upload_protocol = esp-builtin  ; Para programação via USB nativo (se suportado)

build_flags =
    ${esp32.build_flags}
    ;-O3
    -D TERMINAL_NAME=\"supermini\"
    -D TERMINAL_ID=11
    -D RELAY_PIN=2
    -D WIFI       ; Incluir se o Wi-Fi estiver sendo utilizado
    -D NRF24       ; Exemplo de uso de rádio NRF24. Ajuste conforme necessário.
    ;-D RADIO_DUMMY
    -D NRF24_CE=9  ; Pino CE ajustado conforme necessário
    -D NRF24_CSN=10 ; Pino CSN ajustado conforme necessário
    ;-D DEBUG_ON    ; Para habilitar logs de debug
    ;-D WIFI_SSID=\"VIVOFIBRA-A360\"
    ;-D WIFI_PASSWORD=\"6C9FCEC12A\"

lib_deps =
    ${esp32.lib_deps}
    RF24

[env:term_esp32]
platform = espressif32
board = esp32dev  ; Placa mais próxima em configuração
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 160000000L
monitor_speed = 115200
;upload_protocol = esp-builtin
upload_protocol = esptool
;debug_tool = esp-builtin
;upload_protocol = esp-prog
;debug_tool = esp-prog
;upload_port = /dev/cu.usbserial-XXXX  ; No Windows: COMX
;upload_protocol = esp-builtin  ; Para programação via USB nativo (se suportado)

build_flags =
    ${esp32.build_flags}
    -D TERMINAL_NAME=\"esp32\"
    -D TERMINAL_ID=11
    -D RELAY_PIN=2
    -D WIFI       ; Incluir se o Wi-Fi estiver sendo utilizado
    -D NRF24       ; Exemplo de uso de rádio NRF24. Ajuste conforme necessário.
    ;-D RADIO_DUMMY
    -D NRF24_CE=9  ; Pino CE ajustado conforme necessário
    -D NRF24_CSN=10 ; Pino CSN ajustado conforme necessário
    ;-D DEBUG_ON    ; Para habilitar logs de debug
    ;-D WIFI_SSID=\"VIVOFIBRA-A360\"
    ;-D WIFI_PASSWORD=\"6C9FCEC12A\"

lib_deps =
    ${esp32.lib_deps}
    RF24

[env:gw_ttgo_lora]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
monitor_raw = yes
monitor_port = COM4
upload_port = COM4
board_build.mcu = esp32
board_build.f_cpu = 240000000L
build_flags = 
    ${esp32.build_flags}
    ;-D DEBUG_FAUXMO
    ;-D DEBUG_FAUXMO_VERBOSE_UDP
    ;-D DEBUG_FAUXMO_VERBOSE_TCP
    -D TERMINAL_NAME=\"gw\"
    -D TERMINAL_ID=0
    -D RELAY_PIN=0
    -D TTGO
    -D DISPLAYTTGO
    -D LORA32
    -D RADIO_UDP
    -D WIFI
    -D WS
    -D DISPLAY_ENABLED
    -D ALEXA
    -D GATEWAY
    ;-D DEBUG_ON
    ;-D WIFIMANAGER

lib_deps = 
    ${esp32.lib_deps}
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit SSD1306 @ ^2.5.13


[env:term_rboard_rf95]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
monitor_raw = yes
build_flags =
    ${avr.build_flags} 
    -D TERMINAL_NAME=\"pelicano\"
    -D TERMINAL_ID=3
    -D RX_PIN=12
    -D TX_PIN=11
    -D RELAY_PIN=4
    -D TERMINAL
    -D SAVEMEMORY
    -D RF95
lib_deps =
    ${avr.lib_deps}
